FROM node:20-buster-slim 

WORKDIR /app/medusa

COPY package.json .

RUN apt-get update

RUN apt-get update && apt-get install -y bash

RUN apt-get install -y python3

RUN npm install -g npm@latest

RUN npm install -g @medusajs/medusa-cli@latest

RUN npm install --loglevel=error

COPY . .

COPY .env .

RUN chmod +x develop-dev.sh

ENTRYPOINT ["./develop-dev.sh"]