version: "3.8"
services:
  backend:
    image: medusa-store-prod
    container_name: medusa-store-prod
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app/medusa
      - backend_node_modules:/app/medusa/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/medusa-docker
      NODE_ENV: production
      STORE_CORS: http://localhost
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    ports:
      - "9000:9000"

  # backend_admin:
  #   image: medusa-admin-dev
  #   container_name: medusa-admin-dev
  #   restart: always
  #   depends_on:
  #     - backend
  #   environment:
  #     NODE_ENV: production
  #     NODE_OPTIONS: --openssl-legacy-provider
  #   ports:
  #     - "7001:7001"

  # redis:
  #   image: redis
  #   container_name: cache
  #   expose:
  #     - 6379

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medusa-docker

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  # storefront_node_modules:
  backend_node_modules:
  database: