version: "3.8"
services:
  backend:
    image: medusa-store-prod
    container_name: medusa-store-prod
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/medusa-docker
      NODE_ENV: production
      STORE_CORS: http://localhost
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
    ports:
      - "9000:9000"
      - "7001:7001"

  # backend_admin:
  #   image: medusa-admin-dev
  #   container_name: medusa-admin-dev
  #   restart: always
  #   depends_on:
  #     - backend
  #   environment:
  #     NODE_ENV: production
  #     NODE_OPTIONS: --openssl-legacy-provider
  #   ports:
  #     - "7001:7001"

  # redis:
  #   image: redis
  #   container_name: cache
  #   expose:
  #     - 6379

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medusa-docker

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database: